package org.jboss.eap.qe.microprofile.openapi.examples.rest;

import org.eclipse.microprofile.openapi.OASFactory;
import org.eclipse.microprofile.openapi.OASModelReader;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.info.Info;

/**
 * Generates a custom base model to be used by the OpenAPI.
 */
public class OpenApiModelReader implements OASModelReader {
    /**
     * Creates a new {@link Info} instance
     * @return An new {@link OpenAPI} instance that will serve as base for generation
     */
    @Override
    public OpenAPI buildModel() {
        OpenAPI api = OASFactory.createObject(OpenAPI.class);
        Info info = OASFactory.createInfo();
        info.setTermsOfService("Generated by model reader");
        api.setInfo(info);
        return api;
    }
}
